version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: concert-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: concert_db
      MYSQL_USER: concert_user
      MYSQL_PASSWORD: concert_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  rabbitmq:
    image: rabbitmq:3-management
    container_name: concert-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # AMQP 프로토콜
      - "15672:15672" # 관리 UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7-alpine
    container_name: concert-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  rabbitmq_data:
  redis_data: 